export const products = [
  {
    id: 1,
    name: "Pixel 8a",
    category: "Phone",
    description: "Excellent camera, clean Android experience, and strong battery life.",
    price: 41999,
    rating: 4.5,
  },
  {
    id: 2,
    name: "Samsung Galaxy A55",
    category: "Phone",
    description: "Great display, reliable camera, and long battery life.",
    price: 33999,
    rating: 4.4,
  },
  {
    id: 3,
    name: "iPhone 13",
    category: "Phone",
    description: "Excellent camera, strong performance, and premium build quality.",
    price: 41999,
    rating: 4.6,
  },
  {
    id: 4,
    name: "OnePlus Nord CE 4",
    category: "Phone",
    description: "Fast performance, large battery, and fast charging.",
    price: 24999,
    rating: 4.3,
  },
  {
    id: 5,
    name: "MacBook Air M2",
    category: "Laptop",
    description: "Lightweight laptop with excellent performance and battery life.",
    price: 74999,
    rating: 4.8,
  },
  {
    id: 6,
    name: "Dell Inspiron 14",
    category: "Laptop",
    description: "Affordable laptop suitable for productivity and everyday use.",
    price: 49999,
    rating: 4.3,
  },
];