export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({
      error: "Method not allowed",
    });
  }

  try {
    const { preference, products } = req.body;

    if (!preference || !products) {
      return res.status(400).json({
        error: "Preference and products are required",
      });
    }

    const prompt = `
You are an AI product recommendation assistant.

User preference:
${preference}

Available products:
${JSON.stringify(products)}

Recommend 1 to 3 products that best match the user's preference.

Rules:
- Only recommend products from the provided list.
- Never invent a product.
- Use the exact product ID from the provided list.
- Give a short reason explaining why each product matches.
- Return ONLY valid JSON.
- Do not use markdown.
- Do not include any text outside the JSON.

Required format:
{
  "recommendations": [
    {
      "productId": 1,
      "reason": "Short explanation."
    }
  ]
}
`;

    const response = await fetch(
      "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-goog-api-key": process.env.GEMINI_API_KEY,
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: prompt,
                },
              ],
            },
          ],
          generationConfig: {
            temperature: 0.2,
            responseMimeType: "application/json",
          },
        }),
      }
    );

    if (!response.ok) {
  const errorText = await response.text();

  console.error("Gemini API error:", errorText);

  return res.status(500).json({
    error: "Gemini API request failed",
    details: errorText,
  });
}

    const data = await response.json();

    const output =
      data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!output) {
      throw new Error("No response generated by AI");
    }

    const result = JSON.parse(output);

    return res.status(200).json(result);
  } catch (error) {
    console.error("Recommendation error:", error);

    return res.status(500).json({
      error: "Failed to generate recommendations",
    });
  }
}